version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  spring_boot_app:
    image: learningkyljmeeski/test-backend:0.0.1
    container_name: my_spring_boot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_postgres:5432/test_database
      SPRING_DATASOURCE_USERNAME: test_user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
